sudo: false
language: node_js
node_js:
  - "lts/*"
install:
  - npm install
  - gulp build
  - git remote set-url origin git@github.com:idleberg/nsis-build-web.git
  - git add -m Documentation/
  - git commit -am "rebuild from source"
  - git push origin HEAD:master
git:
  depth: 1
branches:
  only:
  - master
cache:
  timeout: 1800
  yarn: true
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false